// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6KBJAHv2KWo9BRnHHSkgd1QQMVMShhfg',
    appId: '1:611395402697:android:841ae30527492a59c78618',
    messagingSenderId: '611395402697',
    projectId: 'chacha-pratha',
    storageBucket: 'chacha-pratha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwL2ifWvcYMLR01bR5f8Twyl8aP_S_S_A',
    appId: '1:611395402697:ios:da9717fe135ecdf3c78618',
    messagingSenderId: '611395402697',
    projectId: 'chacha-pratha',
    storageBucket: 'chacha-pratha.firebasestorage.app',
    iosBundleId: 'com.example.chachaParatha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwL2ifWvcYMLR01bR5f8Twyl8aP_S_S_A',
    appId: '1:611395402697:ios:da9717fe135ecdf3c78618',
    messagingSenderId: '611395402697',
    projectId: 'chacha-pratha',
    storageBucket: 'chacha-pratha.firebasestorage.app',
    iosBundleId: 'com.example.chachaParatha',
  );
}
